In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/DELL/OneDrive/Desktop/RealtyIQ/hyderabad.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9487 entries, 0 to 9486
Data columns (total 55 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SPID                        9487 non-null   int64
 1   PROP_ID                     9487 non-null   object
 2   PREFERENCE                  9487 non-null   object
 3   DESCRIPTION                 9487 non-null   object
 4   PROPERTY_TYPE               9487 non-null   object
 5   CITY                        9487 non-null   object
 6   TRANSACT_TYPE               7911 non-null   float64
 7   OWNTYPE                     9487 non-null   int64
 8   BEDROOM_NUM                 6673 non-null   float64
 9   PRICE_PER_UNIT_AREA         9487 non-null   int64
 10  FURNISH                     9487 non-null   int64
 11  FACING                      9487 non-null   int64
 12  AGE                         9487 non-null   int64
 13  TOTAL_FLOOR                 8911 non-null   float64
 14  FEATURES                    9487 non-null   object
 15  REGISTER_DATE               9487 non-null   object
 16  POSTING_DATE                9245 non-null   float64
 17  UPDATE_DATE                 9487 non-null   float64
 18  CLASS                       9487 non-null   object
 19  RES_COM                     9487 non-null   object
 20  PROP_NAME                   6783 non-null   object
 21  PROPERTY_NUMBER             9487 non-null   int64
 22  MIN_PRICE                   9487 non-null   int64
 23  MAX_PRICE                   9487 non-null   int64
 24  PRICE_SQFT                  9487 non-null   int64
 25  PROJ_ID                     9487 non-null   int64
 26  BUILDING_ID                 9487 non-null   int64
 27  VERIFIED                    9487 non-null   object
 28  MAP_DETAILS                 9487 non-null   object
 29  MIN_AREA_SQFT               9487 non-null   float64
 30  MAX_AREA_SQFT               9487 non-null   float64
 31  AMENITIES                   8142 non-null   object
 32  ALT_TAG                     8260 non-null   object
 33  PRODUCT_TYPE                9487 non-null   object
 34  TOP_USPS                    5372 non-null   object
 35  EXPIRY_DATE                 9487 non-null   object
 36  PROPERTY_TYPE__U            9487 non-null   int64
 37  AREA                        9487 non-null   object
 38  SECONDARY_AREA              9487 non-null   object
 39  PRICE                       9487 non-null   object
 40  PROP_HEADING                9487 non-null   object
 41  VALUE_LABEL                 7927 non-null   object
 42  CLASS_HEADING               9487 non-null   object
 43  CLASS_LABEL                 9487 non-null   object
 44  REGISTER_DATE__U            9487 non-null   object
 45  REGISTERED_DAYS             9487 non-null   object
 46  PRIMARY_TAGS                9487 non-null   object
 47  SECONDARY_TAGS              9487 non-null   object
 48  TOTAL_LANDMARK_COUNT        7812 non-null   float64
 49  FORMATTED_LANDMARK_DETAILS  7812 non-null   object
 50  SOCIETY_NAME                6783 non-null   object
 51  BUILDING_NAME               6783 non-null   object
 52  location                    9487 non-null   object
 53  BALCONY_NUM                 6194 non-null   float64
 54  FLOOR_NUM                   5019 non-null   object
dtypes: float64(9), int64(13), object(33)
memory usage: 4.0+ MB

In [6]:
df.describe()

,SPID,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,POSTING_DATE,...,MIN_PRICE,MAX_PRICE,PRICE_SQFT,PROJ_ID,BUILDING_ID,MIN_AREA_SQFT,MAX_AREA_SQFT,PROPERTY_TYPE__U,TOTAL_LANDMARK_COUNT,BALCONY_NUM
count,9.487000e+03,7911.000000,9487.000000,6673.000000,9.487000e+03,9487.000000,9487.000000,9487.000000,8911.000000,9.245000e+03,...,9.487000e+03,9.487000e+03,9.487000e+03,9487.000000,9.487000e+03,9487.000000,9487.000000,9487.000000,7812.000000,6194.000000
mean,6.972538e+07,1.072178,0.867397,3.048854,2.912723e+05,1.592811,2.911879,2.681248,10.583212,1.688627e+12,...,1.641328e+07,1.666773e+07,2.912723e+05,93758.251080,2.508422e+05,607.489466,615.067107,2.142722,25.265489,1.696965
std,2.778491e+06,0.258799,0.475101,2.301081,8.638714e+06,1.487315,1.565033,2.472537,11.219582,5.385078e+09,...,5.612645e+07,5.624772e+07,8.638714e+06,147271.930926,4.008734e+05,11180.931658,11181.042927,4.988166,18.919282,0.842344
min,1.326949e+07,1.000000,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.652810e+12,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1.672254,1.672254,1.000000,1.000000,0.000000
25%,6.996211e+07,1.000000,1.000000,2.000000,4.685000e+03,0.000000,3.000000,0.000000,3.000000,1.688190e+12,...,2.288756e+06,2.337833e+06,4.685000e+03,0.000000,0.000000e+00,125.419050,125.419050,1.000000,10.000000,1.000000
50%,7.036165e+07,1.000000,1.000000,3.000000,7.999000e+03,2.000000,3.000000,1.000000,5.000000,1.690010e+12,...,7.200000e+06,7.400000e+06,7.999000e+03,0.000000,0.000000e+00,155.891234,161.372511,1.000000,15.000000,2.000000
75%,7.069704e+07,1.000000,1.000000,3.000000,1.500000e+04,2.000000,4.000000,5.000000,15.000000,1.691570e+12,...,1.528761e+07,1.550075e+07,1.500000e+04,237340.000000,4.162110e+05,209.031750,217.393020,3.000000,48.000000,2.000000
max,7.102726e+07,2.000000,4.000000,77.000000,6.000000e+08,4.000000,8.000000,6.000000,56.000000,1.693030e+12,...,2.147484e+09,2.147484e+09,6.000000e+08,413891.000000,1.125563e+06,728433.842400,728433.842400,90.000000,50.000000,4.000000

In [8]:
df.isnull().sum()

SPID                             0
PROP_ID                          0
PREFERENCE                       0
DESCRIPTION                      0
PROPERTY_TYPE                    0
CITY                             0
TRANSACT_TYPE                 1576
OWNTYPE                          0
BEDROOM_NUM                   2814
PRICE_PER_UNIT_AREA              0
FURNISH                          0
FACING                           0
AGE                              0
TOTAL_FLOOR                    576
FEATURES                         0
REGISTER_DATE                    0
POSTING_DATE                   242
UPDATE_DATE                      0
CLASS                            0
RES_COM                          0
PROP_NAME                     2704
PROPERTY_NUMBER                  0
MIN_PRICE                        0
MAX_PRICE                        0
PRICE_SQFT                       0
PROJ_ID                          0
BUILDING_ID                      0
VERIFIED                         0
MAP_DETAILS                      0
MIN_AREA_SQFT                    0
MAX_AREA_SQFT                    0
AMENITIES                     1345
ALT_TAG                       1227
PRODUCT_TYPE                     0
TOP_USPS                      4115
EXPIRY_DATE                      0
PROPERTY_TYPE__U                 0
AREA                             0
SECONDARY_AREA                   0
PRICE                            0
PROP_HEADING                     0
VALUE_LABEL                   1560
CLASS_HEADING                    0
CLASS_LABEL                      0
REGISTER_DATE__U                 0
REGISTERED_DAYS                  0
PRIMARY_TAGS                     0
SECONDARY_TAGS                   0
TOTAL_LANDMARK_COUNT          1675
FORMATTED_LANDMARK_DETAILS    1675
SOCIETY_NAME                  2704
BUILDING_NAME                 2704
location                         0
BALCONY_NUM                   3293
FLOOR_NUM                     4468
dtype: int64

In [10]:
df.duplicated().sum()

0

In [12]:
df.columns

Index(['SPID', 'PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'REGISTER_DATE',
       'POSTING_DATE', 'UPDATE_DATE', 'CLASS', 'RES_COM', 'PROP_NAME',
       'PROPERTY_NUMBER', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT', 'PROJ_ID',
       'BUILDING_ID', 'VERIFIED', 'MAP_DETAILS', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'AMENITIES', 'ALT_TAG', 'PRODUCT_TYPE', 'TOP_USPS',
       'EXPIRY_DATE', 'PROPERTY_TYPE__U', 'AREA', 'SECONDARY_AREA', 'PRICE',
       'PROP_HEADING', 'VALUE_LABEL', 'CLASS_HEADING', 'CLASS_LABEL',
       'REGISTER_DATE__U', 'REGISTERED_DAYS', 'PRIMARY_TAGS', 'SECONDARY_TAGS',
       'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME',
       'BUILDING_NAME', 'location', 'BALCONY_NUM', 'FLOOR_NUM'],
      dtype='object')

In [14]:
realty_df = df.copy()

In [16]:
important_cols = [
    'CITY',
    'AREA',
    'PRICE',
    'PRICE_SQFT',
    'BEDROOM_NUM',
    'PROPERTY_TYPE',
    'FURNISH',
    'AGE',
    'AMENITIES',
    'SOCIETY_NAME'
]

realty_df[important_cols].head()

,CITY,AREA,PRICE,PRICE_SQFT,BEDROOM_NUM,PROPERTY_TYPE,FURNISH,AGE,AMENITIES,SOCIETY_NAME
0,Secunderabad,1215 sq.ft.,69.25 L,5700,2.0,Residential Apartment,2,1,"5,17,20,21,23,24,6",Evolve
1,Hyderabad,1155-1395 sq.ft.,69.3 - 83.7 L,6000,2.0,Residential Apartment,0,5,NaN,Annes Fortune Greenhomes Swan
2,Hyderabad,2880-3000 sq.ft.,Price on Request,0,4.0,Residential Apartment,0,5,NaN,The Olympus
3,Hyderabad,2010-2020 sq.ft.,2.02 - 2.02 Cr,20049,3.0,Residential Apartment,0,5,NaN,The Olympus
4,Hyderabad,2688-3192 sq.ft.,2.42 - 2.87 Cr,8999,3.0,Independent House/Villa,0,5,NaN,Siva Sai Infra Myra

In [18]:
realty_df['PROPERTY_TYPE'].value_counts()

PROPERTY_TYPE
Residential Apartment        4877
Residential Land             2806
Independent House/Villa      1627
Independent/Builder Floor      78
Serviced Apartments            36
Farm House                     35
Studio Apartment               26
Other                           2
Name: count, dtype: int64

In [20]:
realty_df['CITY'].value_counts()

CITY
Hyderabad       8762
Secunderabad     725
Name: count, dtype: int64

In [22]:
realty_df['BEDROOM_NUM'].value_counts().sort_index()

BEDROOM_NUM
1.0      179
2.0     1869
3.0     3250
4.0     1053
5.0      211
6.0       57
7.0       10
8.0        8
9.0        1
10.0       9
12.0       3
14.0       2
15.0       1
18.0       3
20.0       2
26.0       1
28.0       1
35.0       1
36.0       2
38.0       1
42.0       1
46.0       1
47.0       1
48.0       2
50.0       1
51.0       1
55.0       1
77.0       1
Name: count, dtype: int64

In [24]:
realty_df = realty_df[
                (realty_df['BEDROOM_NUM'] >= 1 ) &
                (realty_df['BEDROOM_NUM'] <= 6) ]

In [26]:
realty_df['BEDROOM_NUM'].isnull().sum()

0

In [28]:
realty_df['PRICE'].describe()

count       6619
unique      1714
top       45,000
freq          93
Name: PRICE, dtype: object

In [30]:
realty_df['PRICE'].head(20)

0               69.25 L
1        69.3  - 83.7 L
2      Price on Request
3       2.02  - 2.02 Cr
4       2.42  - 2.87 Cr
5       7.59  - 9.25 Cr
6       1.25  - 1.48 Cr
8        1.8  - 2.43 Cr
9               2.91 Cr
10      2.32  - 2.32 Cr
11      1.35  - 1.42 Cr
12              88.55 L
13        2.5  - 2.5 Cr
14             0 - 1 Cr
15     91.97  - 93.23 L
16              72.12 L
17     Price on Request
19     85.88  - 93.75 L
20      1.08  - 1.28 Cr
21    77.35 L - 1.06 Cr
Name: PRICE, dtype: object

In [32]:
realty_df['PRICE'].value_counts().head(20)

PRICE
45,000              93
50,000              76
60,000              75
55,000              72
Price on Request    64
1.3 Cr              64
40,000              60
1.5 Cr              58
75 L                56
1.15 Cr             54
35,000              53
1.2 Cr              51
1 Cr                51
65,000              50
90 L                48
1.1 Cr              47
1.45 Cr             45
10 Cr               45
2.1 Cr              45
5 Cr                44
Name: count, dtype: int64

In [34]:
import re

In [36]:
# Function to convert single values into numeric format
def convert_to_number(value_str):

    value_str = value_str.strip()

    number = float(re.findall(r"[\d\.]+", value_str)[0])

    # Convert Crores
    if "Cr" in value_str:
        return number * 10000000

    # Convert Lakhs
    elif "L" in value_str:
        return number * 100000

    # Plain numeric values
    else:
        return number


# Main cleaning function
def clean_price(price):

    # Handle null values
    if pd.isnull(price):
        return np.nan

    price = str(price).strip()

    # Handle "Price on Request"
    if "Price on Request" in price:
        return np.nan

    try:

        # Handle ranges
        if "-" in price:

            parts = price.split("-")

            first_part = parts[0].strip()
            second_part = parts[1].strip()

            # If first part has no unit,
            # inherit unit from second part
            if ("Cr" not in first_part) and ("L" not in first_part):

                if "Cr" in second_part:
                    first_part += " Cr"

                elif "L" in second_part:
                    first_part += " L"

            first_value = convert_to_number(first_part)
            second_value = convert_to_number(second_part)

            # If first value is zero,
            # use second value directly
            if first_value == 0:
                return second_value

            # Otherwise take average
            return (first_value + second_value) / 2

        # Handle single values
        else:
            return convert_to_number(price)

    except:
        return np.nan

In [38]:
# Apply cleaning function
realty_df['PRICE_CLEAN'] = realty_df['PRICE'].apply(clean_price)

In [40]:
# Check results
realty_df[['PRICE', 'PRICE_CLEAN']].head(25)

                PRICE  PRICE_CLEAN
0             69.25 L    6925000.0
1      69.3  - 83.7 L    7650000.0
2    Price on Request          NaN
3     2.02  - 2.02 Cr   20200000.0
4     2.42  - 2.87 Cr   26450000.0
5     7.59  - 9.25 Cr   84200000.0
6     1.25  - 1.48 Cr   13650000.0
8      1.8  - 2.43 Cr   21150000.0
9             2.91 Cr   29100000.0
10    2.32  - 2.32 Cr   23200000.0
11    1.35  - 1.42 Cr   13850000.0
12            88.55 L    8855000.0
13      2.5  - 2.5 Cr   25000000.0
14           0 - 1 Cr   10000000.0
15   91.97  - 93.23 L    9260000.0
16            72.12 L    7212000.0
17   Price on Request          NaN
19   85.88  - 93.75 L    8981500.0
20    1.08  - 1.28 Cr   11800000.0
21  77.35 L - 1.06 Cr    9167500.0
23   56.92  - 92.47 L    7469500.0
24    1.54  - 2.21 Cr   18750000.0
28  77.81 L - 1.39 Cr   10840500.0
29   62.96  - 89.36 L    7616000.0
30   Price on Request          NaN

In [42]:
## AREA DATA PREPROCESSING

realty_df['AREA'].head(20)

0           1215 sq.ft.
1     1155-1395  sq.ft.
2     2880-3000  sq.ft.
3     2010-2020  sq.ft.
4     2688-3192  sq.ft.
5     5425-6605  sq.ft.
6     1600-1900  sq.ft.
8     1770-2390  sq.ft.
9           2906 sq.ft.
10    2317-2319  sq.ft.
11    1935-2030  sq.ft.
12          1265 sq.ft.
13          3242 sq.ft.
14    1580-2210  sq.ft.
15    1460-1480  sq.ft.
16          1145 sq.ft.
17           546 sq.ft.
19    1145-1250  sq.ft.
20    1654-1968  sq.ft.
21    1190-1630  sq.ft.
Name: AREA, dtype: object

In [44]:
realty_df['AREA'].value_counts().head(20)

AREA
1350 sq.ft.    114
1800 sq.ft.    105
1200 sq.ft.    104
1100 sq.ft.     77
2000 sq.ft.     66
1250 sq.ft.     65
1500 sq.ft.     62
2100 sq.ft.     60
1600 sq.ft.     59
1150 sq.ft.     56
1492 sq.ft.     52
5000 sq.ft.     51
1283 sq.ft.     48
1300 sq.ft.     46
1440 sq.ft.     44
2235 sq.ft.     42
1993 sq.ft.     42
1314 sq.ft.     41
1742 sq.ft.     41
3000 sq.ft.     40
Name: count, dtype: int64

In [46]:
def clean_area(area):

    if pd.isnull(area):
        return np.nan

    area = str(area).replace("sq.ft.", "").strip()

    try:

        # Handle ranges
        if "-" in area:

            parts = area.split("-")

            first_value = float(parts[0].strip())
            second_value = float(parts[1].strip())

            return (first_value + second_value) / 2

        # Handle single values
        else:
            return float(area)

    except:
        return np.nan

In [48]:
realty_df['AREA_CLEAN'] = realty_df['AREA'].apply(clean_area)

In [50]:
realty_df[['AREA', 'AREA_CLEAN']].head(20)

                 AREA  AREA_CLEAN
0         1215 sq.ft.      1215.0
1   1155-1395  sq.ft.      1275.0
2   2880-3000  sq.ft.      2940.0
3   2010-2020  sq.ft.      2015.0
4   2688-3192  sq.ft.      2940.0
5   5425-6605  sq.ft.      6015.0
6   1600-1900  sq.ft.      1750.0
8   1770-2390  sq.ft.      2080.0
9         2906 sq.ft.      2906.0
10  2317-2319  sq.ft.      2318.0
11  1935-2030  sq.ft.      1982.5
12        1265 sq.ft.      1265.0
13        3242 sq.ft.      3242.0
14  1580-2210  sq.ft.      1895.0
15  1460-1480  sq.ft.      1470.0
16        1145 sq.ft.      1145.0
17         546 sq.ft.       546.0
19  1145-1250  sq.ft.      1197.5
20  1654-1968  sq.ft.      1811.0
21  1190-1630  sq.ft.      1410.0

In [52]:
realty_df['AREA_CLEAN'].describe()

count    6.619000e+03
mean     2.397312e+03
std      1.531319e+04
min      2.700000e+01
25%      1.297000e+03
50%      1.685000e+03
75%      2.256000e+03
max      1.013205e+06
Name: AREA_CLEAN, dtype: float64

In [54]:
realty_df = realty_df[
    (realty_df['AREA_CLEAN'] >= 100) &
    (realty_df['AREA_CLEAN'] <= 20000)
]

In [56]:
realty_df['AREA_CLEAN'].describe()

count     6594.000000
mean      2036.627464
std       1300.956722
min        100.000000
25%       1297.000000
50%       1681.250000
75%       2250.000000
max      18000.000000
Name: AREA_CLEAN, dtype: float64

In [58]:
realty_df['PRICE_PER_SQFT_ENGINEERED'] = (
    realty_df['PRICE_CLEAN'] /
    realty_df['AREA_CLEAN']
)

In [60]:
realty_df[
    ['PRICE_CLEAN', 'AREA_CLEAN', 'PRICE_PER_SQFT_ENGINEERED']
].head(20)

    PRICE_CLEAN  AREA_CLEAN  PRICE_PER_SQFT_ENGINEERED
0     6925000.0      1215.0                5699.588477
1     7650000.0      1275.0                6000.000000
2           NaN      2940.0                        NaN
3    20200000.0      2015.0               10024.813896
4    26450000.0      2940.0                8996.598639
5    84200000.0      6015.0               13998.337490
6    13650000.0      1750.0                7800.000000
8    21150000.0      2080.0               10168.269231
9    29100000.0      2906.0               10013.764625
10   23200000.0      2318.0               10008.628128
11   13850000.0      1982.5                6986.128625
12    8855000.0      1265.0                7000.000000
13   25000000.0      3242.0                7711.289328
14   10000000.0      1895.0                5277.044855
15    9260000.0      1470.0                6299.319728
16    7212000.0      1145.0                6298.689956
17          NaN       546.0                        NaN
19    8981500.0      1197.5                7500.208768
20   11800000.0      1811.0                6515.737162
21    9167500.0      1410.0                6501.773050

In [62]:
realty_df['PRICE_PER_SQFT_ENGINEERED'].describe()

count      6530.000000
mean       8217.268660
std       17482.042311
min           0.000606
25%        3472.222222
50%        6200.000000
75%        9375.000000
max      388571.428571
Name: PRICE_PER_SQFT_ENGINEERED, dtype: float64

In [64]:
realty_df = realty_df[
    (realty_df['PRICE_PER_SQFT_ENGINEERED'] >= 1000) &
    (realty_df['PRICE_PER_SQFT_ENGINEERED'] <= 50000)
]

In [66]:
realty_df['PRICE_PER_SQFT_ENGINEERED'].describe()

count     4888.000000
mean      8468.626249
std       4646.644737
min       1000.000000
25%       5647.826087
50%       7198.958271
75%      10073.173850
max      46296.296296
Name: PRICE_PER_SQFT_ENGINEERED, dtype: float64

In [68]:
realty_df['PRICE_SEGMENT'] = pd.cut(
    realty_df['PRICE_CLEAN'],
    bins=[0, 5000000, 10000000, 20000000, 50000000, 1000000000],
    labels=[
        'Affordable',
        'Mid-Range',
        'Premium',
        'Luxury',
        'Ultra Luxury'
    ]
)

In [70]:
realty_df[
    ['PRICE_CLEAN', 'PRICE_SEGMENT']
].head(20)

    PRICE_CLEAN PRICE_SEGMENT
0     6925000.0     Mid-Range
1     7650000.0     Mid-Range
3    20200000.0        Luxury
4    26450000.0        Luxury
5    84200000.0  Ultra Luxury
6    13650000.0       Premium
8    21150000.0        Luxury
9    29100000.0        Luxury
10   23200000.0        Luxury
11   13850000.0       Premium
12    8855000.0     Mid-Range
13   25000000.0        Luxury
14   10000000.0     Mid-Range
15    9260000.0     Mid-Range
16    7212000.0     Mid-Range
19    8981500.0     Mid-Range
20   11800000.0       Premium
21    9167500.0     Mid-Range
23    7469500.0     Mid-Range
24   18750000.0       Premium

In [72]:
realty_df['PRICE_SEGMENT'].value_counts()

PRICE_SEGMENT
Premium         1696
Mid-Range       1558
Luxury          1004
Ultra Luxury     320
Affordable       310
Name: count, dtype: int64

In [74]:
## TOP PROPERTY TYPES
realty_df['PROPERTY_TYPE'].value_counts().head(10)

PROPERTY_TYPE
Residential Apartment        3581
Independent House/Villa      1247
Independent/Builder Floor      45
Farm House                      8
Studio Apartment                4
Serviced Apartments             3
Name: count, dtype: int64

In [76]:
## PRICE BY PROPERTY TYPE
realty_df.groupby('PROPERTY_TYPE')['PRICE_CLEAN'] \
    .mean() \
    .sort_values(ascending=False)

PROPERTY_TYPE
Independent House/Villa      3.482482e+07
Farm House                   1.689988e+07
Residential Apartment        1.455320e+07
Independent/Builder Floor    1.170444e+07
Serviced Apartments          9.090667e+06
Studio Apartment             2.925000e+06
Name: PRICE_CLEAN, dtype: float64

In [78]:
## PRICE BY BEDROOM COUNT
realty_df.groupby('BEDROOM_NUM')['PRICE_CLEAN'] \
    .mean() \
    .sort_values()

BEDROOM_NUM
1.0    4.480862e+06
2.0    8.029507e+06
3.0    1.684178e+07
4.0    3.938576e+07
5.0    6.490032e+07
6.0    6.645962e+07
Name: PRICE_CLEAN, dtype: float64

In [80]:
## PRICE SEGMENT DISTRIBUTION
realty_df['PRICE_SEGMENT'].value_counts()

PRICE_SEGMENT
Premium         1696
Mid-Range       1558
Luxury          1004
Ultra Luxury     320
Affordable       310
Name: count, dtype: int64

In [82]:
## AVG PRICE PER SQFT BY PROPERTY TYPE
realty_df.groupby('PROPERTY_TYPE')['PRICE_PER_SQFT_ENGINEERED'] \
    .mean() \
    .sort_values(ascending=False)

PROPERTY_TYPE
Independent House/Villa      11096.676066
Independent/Builder Floor     7765.004996
Residential Apartment         7574.801149
Studio Apartment              7144.444444
Serviced Apartments           5808.270301
Farm House                    4537.415359
Name: PRICE_PER_SQFT_ENGINEERED, dtype: float64

In [84]:
## FURNISHED VS UNFURNISHED ANALYSIS
realty_df.groupby('FURNISH')['PRICE_CLEAN'] \
    .mean()

FURNISH
0    2.196696e+07
1    2.467313e+07
2    1.794939e+07
4    2.306402e+07
Name: PRICE_CLEAN, dtype: float64

In [86]:
## CITY-WISE PRICE ANALYSIS
realty_df.groupby('CITY')['PRICE_CLEAN'] \
    .mean() \
    .sort_values(ascending=False)

CITY
Hyderabad       2.025496e+07
Secunderabad    1.348083e+07
Name: PRICE_CLEAN, dtype: float64

In [88]:
## PROPERTY TYPE ANALYTICS TABLE
property_type_analysis = (
    realty_df.groupby('PROPERTY_TYPE')
    .agg({
        'PRICE_CLEAN': ['mean', 'median', 'count'],
        'PRICE_PER_SQFT_ENGINEERED': 'mean',
        'AREA_CLEAN': 'mean'
    })
)

property_type_analysis

                            PRICE_CLEAN                    \
                                   mean      median count
PROPERTY_TYPE
Farm House                 1.689988e+07  11500000.0     8
Independent House/Villa    3.482482e+07  21000000.0  1247
Independent/Builder Floor  1.170444e+07   8500000.0    45
Residential Apartment      1.455320e+07  11000000.0  3581
Serviced Apartments        9.090667e+06   8900000.0     3
Studio Apartment           2.925000e+06   2850000.0     4

                          PRICE_PER_SQFT_ENGINEERED   AREA_CLEAN
                                               mean         mean
PROPERTY_TYPE
Farm House                              4537.415359  5547.250000
Independent House/Villa                11096.676066  2873.385726
Independent/Builder Floor               7765.004996  1612.955556
Residential Apartment                   7574.801149  1767.264870
Serviced Apartments                     5808.270301  1579.666667
Studio Apartment                        7144.444444   475.000000

In [90]:
## BEDROOM ANALYTICS TABLE
bedroom_analysis = (
    realty_df.groupby('BEDROOM_NUM')
    .agg({
        'PRICE_CLEAN': ['mean', 'median', 'count'],
        'AREA_CLEAN': 'mean',
        'PRICE_PER_SQFT_ENGINEERED': 'mean'
    })
)

bedroom_analysis

              PRICE_CLEAN                     AREA_CLEAN  \
                     mean      median count         mean
BEDROOM_NUM
1.0          4.480862e+06   3200000.0    29   823.672414
2.0          8.029507e+06   7192000.0  1473  1247.082485
3.0          1.684178e+07  14150000.0  2417  1967.076127
4.0          3.938576e+07  29800000.0   760  3223.426974
5.0          6.490032e+07  50000000.0   157  4582.808917
6.0          6.645962e+07  53550000.0    52  4821.538462

            PRICE_PER_SQFT_ENGINEERED
                                 mean
BEDROOM_NUM
1.0                       6538.948909
2.0                       6372.719086
3.0                       8293.359312
4.0                      11763.589762
5.0                      13833.407856
6.0                      12707.262755

In [92]:
## PRICE SEGMENT ANALYTICS
segment_analysis = (
    realty_df.groupby('PRICE_SEGMENT')
    .agg({
        'PRICE_CLEAN': ['mean', 'count'],
        'AREA_CLEAN': 'mean',
        'PRICE_PER_SQFT_ENGINEERED': 'mean'
    })
)

segment_analysis

C:\Users\DELL\AppData\Local\Temp\ipykernel_11772\1255402432.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  realty_df.groupby('PRICE_SEGMENT')

                PRICE_CLEAN         AREA_CLEAN PRICE_PER_SQFT_ENGINEERED
                       mean count         mean                      mean
PRICE_SEGMENT
Affordable     4.284823e+06   310  1110.300000               4019.803255
Mid-Range      7.695733e+06  1558  1352.643132               5928.167904
Premium        1.431236e+07  1696  1821.122642               8203.089222
Luxury         2.937425e+07  1004  2910.817729              10702.203521
Ultra Luxury   9.112078e+07   320  4914.348437              19546.777647

In [94]:
## CITY ANALYTICS
city_analysis = (
    realty_df.groupby('CITY')
    .agg({
        'PRICE_CLEAN': ['mean', 'median', 'count'],
        'AREA_CLEAN': 'mean',
        'PRICE_PER_SQFT_ENGINEERED': 'mean'
    })
)

city_analysis

               PRICE_CLEAN                     AREA_CLEAN  \
                      mean      median count         mean
CITY
Hyderabad     2.025496e+07  13000000.0  4480  2079.148214
Secunderabad  1.348083e+07   9544250.0   408  1766.430147

             PRICE_PER_SQFT_ENGINEERED
                                  mean
CITY
Hyderabad                  8586.187380
Secunderabad               7177.758936

In [96]:
realty_df.to_csv(
    'cleaned_real_estate_data.csv',
    index=False
)

In [98]:
property_type_analysis.to_csv(
    'property_type_analysis.csv'
)

In [100]:
bedroom_analysis.to_csv(
    'bedroom_analysis.csv'
)

In [102]:
segment_analysis.to_csv(
    'segment_analysis.csv'
)

In [104]:
city_analysis.to_csv(
    'city_analysis.csv'
)

In [106]:
realty_df.to_csv(
    'final_realty_mysql_ready.csv',
    index=False,
    encoding='utf-8',
    quoting=1
)